export const FETCH_ARTISTS_SUCCESS = "FETCH_ARTISTS_SUCCESS";
export const FETCH_HISTORIES_SUCCESS = "FETCH_HISTORIES_SUCCESS";
export const FETCH_TRACKS_SUCCESS = "FETCH_TRACKS_SUCCESS";
export const FETCH_ALBUMS_SUCCESS = "FETCH_ALBUMS_SUCCESS";
export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_ERROR = "FETCH_ERROR";

export const CREATE_ARTIST_SUCCESS = "CREATE_ARTIST_SUCCESS";
export const CREATE_ALBUM_SUCCESS = "CREATE_ALBUM_SUCCESS";
export const CREATE_TRACK_SUCCESS = "CREATE_TRACK_SUCCESS";

export const FETCH_ADMIN_ARTISTS_SUCCESS = "FETCH_ADMIN_ARTISTS_SUCCESS";
export const FETCH_ADMIN_ALBUMS_SUCCESS = "FETCH_ADMIN_ALBUMS_SUCCESS";
export const FETCH_ADMIN_TRACKS_SUCCESS = "FETCH_ADMIN_TRACKS_SUCCESS";
export const FETCH_PUBLISH_SUCCESS = "FETCH_PUBLISH_SUCCESS";
export const FETCH_DELETE_SUCCESS = "FETCH_DELETE_SUCCESS";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";